version: "3.9"

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    build: ../backend/it_events
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    env_file:
      - ./.env

  frontend:
    build: ../frontend
    depends_on:
      - backend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
    depends_on:
      - frontend

volumes:
  static_value:
  media_value:
  db_value: