version: "3.9"

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "username", '-d', 'default_database' ]
      interval: 5s
      retries: 5
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: asterrus/it_events_backend:v1.0.first
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    env_file:
      - ./.env

  frontend:
    image: asterrus/it_events_frontend:v1.0.first
    depends_on:
      - backend
    volumes:
      - front_value:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - front_value:/usr/share/nginx/html/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
      - backend
volumes:
  static_value:
  media_value:
  db_value:
  front_value: