version: "3.9"


services:

  db:
    image: postgres:13.0-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", '-d', 'postgres' ]
      interval: 5s
      retries: 5
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: asterrus/it_events_backend:v1.0.first
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    env_file:
      - ./.env

  frontend:
    image: asterrus/it_events_frontend:v1.0.first
    depends_on:
      - backend
    volumes:
      - front_value:/app/result_build/

  
volumes:
  static_value:
  media_value:
  db_value:
  front_value: